[package]
name = "embassy-riscv"
version = "0.1.0"
edition = "2021"

[dependencies]
embassy-macros  = { version = "0.1.0", path = "../embassy-macros"}
embassy-hal-common = { version = "0.1.0", path = "../embassy-hal-common", features = [] }
atomic-polyfill = "0.1.5"
